FROM golang:1.8

# Install beego and the bee dev tool
#RUN go get github.com/julienschmidt/httprouter && go get github.com/romana/rlog && go get gopkg.in/mgo.v2 && go get github.com/mauidude/go-readability && go get github.com/rs/cors

# Expose the application on port 8080
#EXPOSE 8080

# Set the entry point of the container to the bee command that runs the
# application and watches for changes
#CMD ["go", "run"]


# Create the directory where the application will reside
RUN mkdir /app

# Copy the application files (needed for production)
ADD bin/the-informer.exe /app/the-informer
#ADD views /app/views
#ADD conf /app/conf

# Set the working directory to the app directory
WORKDIR /app

# Expose the application on port 8080.
# This should be the same as in the app.conf file
EXPOSE 8080

# Set the entry point of the container to the application executable
ENTRYPOINT /app/the-informer
